apiVersion: apps/v1
kind: Deployment
metadata:
  name: digit-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digit-api
  template:
    metadata:
      labels:
        app: digit-api
    spec:
      containers:
      - name: digit-api
        image: gcr.io/vcc-final-project-456615/digit-api:latest  # Update this to your image location
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: digit-service
spec:
  selector:
    app: digit-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: digit-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: digit-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
