name: Cloud Deployment

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_REPO: gcr.io/vcc-final-project-456615/digit-api

jobs:
  terraform:
    name: Terraform - Build Google Cloud Cluster
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.IMAGE_REPO }}:${{ github.sha }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

  deploy:
    name: Deploy to GKE
    needs: terraform
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Get GKE Credentials
        id: gke-creds
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ vars.CLUSTER_NAME }}       # You can define this as a repository secret or variable.
          location: ${{ vars.CLUSTER_ZONE }}            # Define these as needed.
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f templates/kubernetes/kubernetes.yml
